# action.yml ────────────────────────────────────────────────────────────────
name: "RSync Artifacts"
description: >
  Backup or restore multiple folders to "/<base | $HOME/.artifacts>/<target>/<folder>/".

author: "Daniel Pfisterer <info@daniel-pfisterer.de>"

inputs:
  mode:
    description: "'push' or 'pull'"
    required: true
  target:
    description: "Target directory under the base path"
    required: true
  source:
    description: "Comma-separated list of folders"
    required: true
  base:
    description: "Root artifact directory (defaults to $HOME/.artifacts)"
    required: false
  delete:
    description: "If 'true', add --delete (push only)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - id: run-script
      shell: bash
      run: |
        set -euo pipefail

        # Ensure the script is executable
        chmod +x "${{ github.action_path }}/src/artifacts.sh"

        # Build argument list
        ARGS=(
          "${{ inputs.mode }}"
          --target="${{ inputs.target }}"
          --source="${{ inputs.source }}"
        )

        # Optional flags
        if [[ -n "${{ inputs.base }}" ]]; then
          ARGS+=(--base="${{ inputs.base }}")
        fi

        if [[ "${{ inputs.delete }}" == "true" ]]; then
          ARGS+=(--delete)
        fi

        # Execute
        "${{ github.action_path }}/src/artifacts.sh" "${ARGS[@]}"
        
branding:
  icon: "upload-cloud"
  color: "blue"
